### ISSUE TITLE
copy(model::Model)  does not copy the solution information

### ISSUE THREAD

**Issue by YankaiCao** [jump-dev/Gurobi.jl#100]
If I create the model and then optimize it, Then I copy it with function `copy(model::Model)`, I cannot get solution or basis from the copy of model but I can get from the original model.

**Comment by blegat** [comment]
From the [MPB doc](http://mathprogbasejl.readthedocs.io/en/latest/solverinterface.html): "`copy` Copies the model m by replicating the solver internal model, callbacks are not copied."
When copying a copy we call the corresponding `copy` operation of the Gurobi C-interface to the internal model (see https://github.com/JuliaOpt/Gurobi.jl/blob/6155881b5b909edfc0947e27fbc063eb33c85f6c/src/grb_model.jl#L81). According to what you say, it seems that [this operation](https://www.gurobi.com/documentation/7.0/refman/py_model_copy.html) does not copy the solution but only the model.

We could add the requirement in the MPB doc that solution should also be copied even if the internal model does not do it which will force us to do additional work in this package to do copy this manually. I would personally not be in favor of doing so since I prefer it when the MPB wrappers remain thin layers and I wouldn't expect the copy of a model to copy solutions (and it seems to also be the interpretation of Gurobi).

**Comment by joaquimg** [comment]
I agree that we should keep the wrapper thin and do not copy the solution. Perhaps adding in the docs: "solution is not copied" or something like that...
