### ISSUE TITLE
get_optimizer_attribute(m, "LogFile") fails in GRBgetstrparam

### ISSUE THREAD

**Issue by xhub** [jump-dev/Gurobi.jl#442]
MWE: in the REPL, executing
```
m = direct_model(Gurobi.Optimizer())
set_optimizer_attribute(m, "LogFile", tempname())
get_optimizer_attribute(m, "LogFile")
```
results in
```
ERROR: MethodError: no method matching unsafe_convert(::Type{Ptr{Int8}}, ::Base.RefValue{Ptr{Int8}})
Closest candidates are:
  unsafe_convert(::Type{Ptr{T}}, ::PermutedDimsArray{T}) where T at /scratch/julia-1.7.1/share/julia/base/permuteddimsarray.jl:54
  unsafe_convert(::Type{Ptr{T}}, ::Base.ReinterpretArray{T, N, S, A} where {N, A<:(AbstractArray{S})}) where {T, S} at /scratch/julia-1.7.1/share/julia/base/reinterpretarray.jl:315
  unsafe_convert(::Type{Ptr{T}}, ::StaticArrays.SizedArray) where T at ~/.julia/packages/StaticArrays/deP1N/src/SizedArray.jl:129
  ...
Stacktrace:
 [1] GRBgetstrparam(env::Ptr{Nothing}, paramname::String, valueP::Base.RefValue{Ptr{Int8}})
   @ Gurobi ~/.julia/packages/Gurobi/A9YqC/src/gen95/libgrb_api.jl:690
 [2] get(model::Gurobi.Optimizer, raw::MathOptInterface.RawOptimizerAttribute)
   @ Gurobi ~/.julia/packages/Gurobi/A9YqC/src/MOI_wrapper/MOI_wrapper.jl:624
 [3] get(model::Model, attr::MathOptInterface.RawOptimizerAttribute)
   @ JuMP ~/.julia/packages/JuMP/2IF9U/src/JuMP.jl:1261
 [4] get_optimizer_attribute
   @ ~/.julia/packages/JuMP/2IF9U/src/JuMP.jl:971 [inlined]
 [5] get_optimizer_attribute(model::Model, name::String)
   @ JuMP ~/.julia/packages/JuMP/2IF9U/src/JuMP.jl:949
 [6] top-level scope
   @ REPL[15]:1
```

Gurobi 9.5
Julia version: 1.7.1
[2e9cd046] Gurobi v0.10.1
[4076af6c] JuMP v0.22.1
[b8f27783] MathOptInterface v0.10.6

**Comment by odow** [comment]
Annoying. Looks like `GRBgetstrparam`:
https://github.com/jump-dev/Gurobi.jl/blob/1008e8cf2e11ec0e8ed846f55757ffe9aefd5c14/src/gen95/libgrb_api.jl#L689-L691
has a different signature to `GRBgetstrattr`
https://github.com/jump-dev/Gurobi.jl/blob/1008e8cf2e11ec0e8ed846f55757ffe9aefd5c14/src/gen95/libgrb_api.jl#L101-L103

Looks like we're missing a test as well (now that we have coverage):
<img width="813" alt="image" src="https://user-images.githubusercontent.com/8177701/148281701-340ffa5f-d627-405a-bb9b-8e7311fa11da.png">

Rather than passing 
https://github.com/jump-dev/Gurobi.jl/blob/1008e8cf2e11ec0e8ed846f55757ffe9aefd5c14/src/MOI_wrapper/MOI_wrapper.jl#L623-L626
we probably need 
```Julia
valueP = Vector{Cchar}(undef, GRB_MAX_STRLEN)
ret = GRBgetstrparam(env, param, valueP)
_check_ret(env, ret)
GC.@preserve valueP begin
    return unsafe_string(pointer(valueP))
end
```
but I haven't tried or tested this.

I'll review a PR, but I don't have time to look at this myself.

**Comment by odow** [comment]
@simonbowly: any reason why GRBgetstrparam takes `char *` but GRBgetstrattr takes `char **`?

https://www.gurobi.com/documentation/9.5/refman/c_getstrparam.html
https://www.gurobi.com/documentation/9.5/refman/c_getstrattr.html
