### ISSUE TITLE
High level API QP

### ISSUE THREAD

**Issue by alexe15** [jump-dev/Gurobi.jl#478]
Doe the high-level API for QPs still work? When I try to run the code from [here](https://docs.juliahub.com/Gurobi/do9v6/0.7.7/) I get the error 

ERROR: UndefVarError: gurobi_model not defined.

**Comment by odow** [comment]
> Does the high-level API for QPs still work?

No. Use JuMP or MathOptInterface instead.

> When I try to run the code from [here](https://docs.juliahub.com/Gurobi/do9v6/0.7.7/) I get the error

That documentation is old and out-of-date. (It's for Gurobi.jl v0.7.7, the current version is 0.11.2)

**Comment by odow** [comment]
Closing because there's nothing actionable.

JuMP documentation has examples of quadratic problems: 
 * https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/qcp/
 * https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/portfolio/

Just use `Gurobi.Optimizer` instead of `Ipopt.Optimizer`.

If you have follow-up questions, please post on the community forum and we can help out: https://discourse.julialang.org/c/domain/opt/13
